title: Vlan Trunking Lab

nav:
  - label: Work
    url: https://edidevi.github.io/My-Work/
  - label: GitHub
    url: https://github.com/Edidevi

footer:
  hosted_on: GitHub Pages
  hosted_url: https://pages.github.com


defaults:
  - scope:
      path: ""
    values:
      layout: "troubleshooting"
